- name: post_ldconfig_notify
  become: true
  community.general.ini_file:
    path: /etc/wsl.conf
    section: automount
    option: "{{ item.option  }}"
    value: "{{ item.value }}"
    create: true
    state: present
  loop:
    - option: ldconfig
      value: 'false'
