- name: 日本語パッケージのインストール
  become: true
  ansible.builtin.apt:
    name:
      - fcitx5
      - fcitx5-frontend-gtk2
      - fcitx5-frontend-gtk3
      - fcitx5-mozc
      - kde-config-fcitx5
    update_cache: yes
