---
- name: コマンドを実行する1
  become: true
  ansible.builtin.shell:
    cmd: sudo wget https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -q -P /etc/apt/trusted.gpg.d/
- name: コマンドを実行する2
  become: true
  ansible.builtin.shell:
    cmd: sudo wget https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -q -P /etc/apt/trusted.gpg.d/
- name: コマンドを実行する3
  become: true
  ansible.builtin.shell:
    cmd: sudo wget https://www.ubuntulinux.jp/sources.list.d/jammy.list -q -O /etc/apt/sources.list.d/ubuntu-ja.list
- name: 日本語パッケージのインストール1
  become: true
  ansible.builtin.apt:
    update_cache: yes
- name: 日本語パッケージのインストール
  become: true
  ansible.builtin.apt:
    name:
      - ubuntu-defaults-ja
      - manpages-ja
      - manpages-ja-dev
    update_cache: yes
