---
- name: Ubuntu Remix リポジトリーGPG
  become: true
  ansible.builtin.apt_key:
    url: https://www.ubuntulinux.jp/{{item}}
    state: present
  loop:
    - ubuntu-jp-ppa-keyring.gpg
    - ubuntu-ja-archive-keyring.gpg
- name: リポジトリーの登録
  become: true
  ansible.builtin.get_url:
    url: https://www.ubuntulinux.jp/sources.list.d/jammy.list
    dest: /etc/apt/sources.list.d/ubuntu-ja.list
- name: 日本語パッケージのインストール
  become: true
  ansible.builtin.apt:
    name:
      - ubuntu-defaults-ja
    update_cache: yes
