---
- name: locale ja_JP.UTF-8の作成
  become: true
  community.general.locale_gen:
    name: ja_JP.UTF-8
- name: locale設定
  become: true
  ansible.builtin.shell: update-locale LANG=ja_JP.UTF-8
  when: ansible_env.LANG | default('') != 'ja_JP.UTF-8'

