---
- name: リポジトリーGPG
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    keyring: "{{ keying_path }}"
    state: present
- name: リポジトリーの登録
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{dpkg_arch}} signed-by={{ keying_path }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
- name: Dockerインストール
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    update_cache: yes
    state: present
  notify: post_docker_notify

