---
- name: wslconf
  become: true
  community.general.ini_file:
    path: /etc/wsl.conf
    section: boot
    option: "{{ item.option  }}"
    value: "{{ item.value }}"
    create: true
    state: present
  loop:
    - option: command
      value: 'service docker start'
    # なぜかsystemdを有効にするとdockerのデーモン起動に失敗する
    # - option: systemd
    #   value: 'true'
